export const UPDATE_BOOLEAN_LAWS_LIST = 'UPDATE_BOOLEAN_LAWS_LIST'

export const UPDATE_BOOLEAN_EXPRESSION = 'UPDATE_BOOLEAN_EXPRESSION'
export const RESET_BOOLEAN_EXPRESSION = 'RESET_BOOLEAN_EXPRESSION'
