export const UPDATE_BOOLEAN_LAWS_LIST = 'UPDATE_BOOLEAN_LAWS_LIST'

export const UPDATE_SIMPLIFIED_EXPRESSION = 'UPDATE_SIMPLIFIED_EXPRESSION'
export const RESET_SIMPLIFIED_EXPRESSION = 'RESET_SIMPLIFIED_EXPRESSION'

export const UPDATE_EXPRESSION_DATA = 'UPDATE_EXPRESSION_DATA'
export const RESET_EXPRESSION_DATA = 'RESET_EXPRESSION_DATA'